name: sqldef
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - uses: actions/checkout@v2

      - run: docker-compose up -d
      - run: make test
        env:
          MYSQL_HOST: 127.0.0.1
          PGHOST: 127.0.0.1
          PGSSLMODE: disable

  package:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - uses: actions/checkout@v2

      - run: make package

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - uses: actions/checkout@v2

      - run: make package
      - name: Release
        run: |
          export VERSION=$(echo "$GITHUB_REF" | sed -e 's!refs/tags/!!')
          curl -L "https://github.com/tcnksm/ghr/releases/download/${GHR_VERSION}/ghr_${GHR_VERSION}_linux_amd64.tar.gz" | tar xvz
          "ghr_${GHR_VERSION}_linux_amd64/ghr" -u k0kubun -r sqldef -replace -n "$VERSION" "$VERSION" package/
        env:
          GHR_VERSION: v0.13.0
          GITHUB_TOKEN: ${{ secrets.githubtoken }}
