name: sqldef
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
env:
  OSXCROSS_REVISION: 4287300a5c96397a2ee9ab3942e66578a1982031
  XCODE_VERSION: '12.4'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - sqlite3def
          - mssqldef
        include:
          - target: mysqldef
            mysql_version: '5.7'
          - target: mysqldef
            mysql_version: '8.0'
          - target: psqldef
            postgres_version: 10
          - target: psqldef
            postgres_version: 11
          - target: psqldef
            postgres_version: 12
          - target: psqldef
            postgres_version: 13
          - target: psqldef
            postgres_version: 14
      fail-fast: false
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3

      - run: docker-compose up -d
        env:
          MYSQL_VERSION: ${{ matrix.mysql_version }}
          POSTGRES_VERSION: ${{ matrix.postgres_version }}
      - run: make deps
      - run: make test-${{ matrix.target }}

  package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { GOOS: linux,   GOARCH: amd64, EXT: tar.gz, ZIG_CFLAGS: '-target x86_64-linux' }
          - { GOOS: linux,   GOARCH: '386', EXT: tar.gz, ZIG_CFLAGS: '-target i386-linux' }
          - { GOOS: linux,   GOARCH: arm64, EXT: tar.gz, ZIG_CFLAGS: '-target aarch64-linux' }
          - { GOOS: linux,   GOARCH: arm,   EXT: tar.gz, ZIG_CFLAGS: '-target arm-linux-musleabi' }
          - { GOOS: windows, GOARCH: amd64, EXT: zip,    ZIG_CFLAGS: '-target x86_64-windows' }
          - { GOOS: windows, GOARCH: '386', EXT: zip,    ZIG_CFLAGS: '-target i386-windows' }
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3

      - name: Download MacOSX SDK
        run: make MacOSX.sdk
        if: ${{ matrix.GOOS == 'darwin' }}

      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - name: make package-${{ matrix.EXT }}
        run: |
          make package-${{ matrix.EXT }} GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} "ZIG_CFLAGS=${{ matrix.ZIG_CFLAGS }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sqldef-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: package/*def_${{ matrix.GOOS }}_${{ matrix.GOARCH }}.${{ matrix.EXT }}

  macos-sdk:
    runs-on: macos-latest
    steps:
      - uses: actions/cache@v2
        id: macos-sdk-cache
        with:
          key: macos-sdk-${{ env.OSXCROSS_REVISION }}-${{ env.XCODE_VERSION }}
          path: osxcross/tarballs
      - name: Package MacOSX SDK
        if: steps.macos-sdk-cache.outputs.cache-hit != 'true'
        run: |
          curl -sSLf https://github.com/tpoechtrager/osxcross/archive/${OSXCROSS_REVISION}.tar.gz | tar zxf -
          mv osxcross-${OSXCROSS_REVISION} osxcross
          cd osxcross
          XCODEDIR=/Applications/Xcode_${XCODE_VERSION}.app tools/gen_sdk_package.sh
          mv MacOSX*.sdk.tar.xz tarballs/

  osxcross:
    runs-on: ubuntu-latest
    needs:
      - macos-sdk
    steps:
      - name: Download osxcross
        run: |
          curl -sSLf https://github.com/tpoechtrager/osxcross/archive/${OSXCROSS_REVISION}.tar.gz | tar zxf -
          mv osxcross-${OSXCROSS_REVISION} osxcross
      - uses: actions/cache@v2
        with:
          key: macos-sdk-${{ env.OSXCROSS_REVISION }}-${{ env.XCODE_VERSION }}
          path: osxcross/tarballs
      - uses: actions/cache@v2
        id: osxcross-cache
        with:
          key: osxcross-${{ runner.os }}-${{ env.OSXCROSS_REVISION }}-${{ env.XCODE_VERSION }}
          path: osxcross/target
      - name: Build osxcross
        if: steps.osxcross-cache.outputs.cache-hit != 'true'
        run: UNATTENDED=1 ./build.sh
        working-directory: osxcross

  osxcross-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { GOOS: darwin, GOARCH: amd64, EXT: zip, CC: x86_64-apple-darwin20.2-clang }
          - { GOOS: darwin, GOARCH: arm64, EXT: zip, CC: aarch64-apple-darwin20.2-clang }
      fail-fast: false
    needs:
      - osxcross
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - uses: actions/cache@v2
        id: osxcross-cache
        with:
          key: osxcross-${{ runner.os }}-${{ env.OSXCROSS_REVISION }}-${{ env.XCODE_VERSION }}
          path: osxcross/target

      - name: make package-${{ matrix.EXT }}
        run: |
          export PATH="$PWD/osxcross/target/bin:$PATH"
          make package-${{ matrix.EXT }} GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} CC=${{ matrix.CC }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sqldef-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: package/*def_${{ matrix.GOOS }}_${{ matrix.GOARCH }}.${{ matrix.EXT }}

  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - package
      - osxcross-build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - { uses: actions/download-artifact@v3, with: { name: sqldef-linux-amd64,   path: package/ } }
      - { uses: actions/download-artifact@v3, with: { name: sqldef-linux-386,     path: package/ } }
      - { uses: actions/download-artifact@v3, with: { name: sqldef-linux-arm64,   path: package/ } }
      - { uses: actions/download-artifact@v3, with: { name: sqldef-linux-arm,     path: package/ } }
      - { uses: actions/download-artifact@v3, with: { name: sqldef-darwin-amd64,  path: package/ } }
      - { uses: actions/download-artifact@v3, with: { name: sqldef-darwin-arm64,  path: package/ } }
      - { uses: actions/download-artifact@v3, with: { name: sqldef-windows-amd64, path: package/ } }
      - { uses: actions/download-artifact@v3, with: { name: sqldef-windows-386,   path: package/ } }

      - name: Release binaries
        run: |
          export VERSION=$(echo "$GITHUB_REF" | sed -e 's!refs/tags/!!')
          curl -L "https://github.com/tcnksm/ghr/releases/download/${GHR_VERSION}/ghr_${GHR_VERSION}_linux_amd64.tar.gz" | tar xvz
          "ghr_${GHR_VERSION}_linux_amd64/ghr" -u k0kubun -r sqldef -replace -n "$VERSION" "$VERSION" package/
        env:
          GHR_VERSION: v0.13.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          repository: sqldef/homebrew-sqldef
          ssh-key: ${{ secrets.HOMEBREW_DEPLOY_KEY }}
          path: ./homebrew-sqldef
      - name: Update homebrew
        run: |
          set -x
          cd ./homebrew-sqldef
          VERSION=$(echo "$GITHUB_REF" | sed -e 's!refs/tags/!!')
          sed -i -e "s/tag: '.*'/tag: '$VERSION'/" mysqldef.rb psqldef.rb
          git add .
          if ! git diff-index --quiet HEAD --; then
            git config --global user.email "k0kubun@github.com"
            git config --global user.name "sqldef"
            git commit -m "Version $VERSION"
            git push origin master
          fi
